<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Logout</name>
   <tag></tag>
   <elementGuidId>59fc50db-d48f-4ffd-b7da-e1b746246e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[5]/header/div/div[3]/div[3]/div/div/div/div[2]/button/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>06b76533-8e25-4592-a1c8-b40a54661b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Text_root__M6tno</value>
      <webElementGuid>caa7dcd4-ced1-4b01-b72c-5be3b1774679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>8ca67aa0-b415-45cb-a556-e6ed60e4e167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/header[@class=&quot;bg-c-gray-700 z-20 text-white fixed top-0 inset-x-0 h-[66px] print:hidden&quot;]/div[@class=&quot;flex justify-end px-2 xs:px-3 sm:px-s30 py-2 relative h-full items-center&quot;]/div[@class=&quot;flex justify-end items-center h-[40px] z-[1] space-x-s5 w-1/2&quot;]/div[3]/div[@class=&quot;Dropdown_container__5LCLe h-[40px]&quot;]/div[@class=&quot;Dropdown_root__lsKzD Dropdown_dark__sLn+X Dropdown_right__1rLfh mt-s5 overflow-y-auto list-unstyled z-[2]&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[2]/button[@class=&quot;Button_root__0RbKd Button_ghost__tLrp+&quot;]/div[@class=&quot;flex items-center w-56 text-white space-x-s20 px-s20 py-s10&quot;]/p[@class=&quot;Text_root__M6tno&quot;]</value>
      <webElementGuid>e5573a56-d0cf-4340-9a96-89a63c0b84e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/header/div/div[3]/div[3]/div/div/div/div[2]/button/div/p</value>
      <webElementGuid>dbbf9afc-5720-4cce-b4d5-36343e691c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/p</value>
      <webElementGuid>65997adf-28c6-47e8-ab80-ee61880727da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>3cdf744b-7f5f-4440-a057-eea0b2b3fdec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
