<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>2305c31a-9902-45c0-9aee-ba62bb64c907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button_root__0RbKd.Button_primary__NGIIN.Button_xl__w2v80</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22582525-d5f6-4935-9035-baff2d83b840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca170605-918c-46f9-b59e-16c45eb17d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_root__0RbKd Button_primary__NGIIN Button_xl__w2v80</value>
      <webElementGuid>bde98bf9-2e08-4814-a74f-446a817d5786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>872ecb87-6f6b-493d-a069-8723d80c6416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/main[@class=&quot;flex&quot;]/div[@class=&quot;mt-s60 w-full duration-200 transition-all ml-auto content-width-minus-sidebar px-2 sm:px-8 pb-8&quot;]/div[1]/form[1]/section[@class=&quot;PageHeader_root__FRduB !justify-start&quot;]/div[@class=&quot;h-full flex items-start w-full justify-end&quot;]/div[@class=&quot;w-full min-w-full flex justify-end&quot;]/div[1]/div[@class=&quot;flex space-x-1 sm:space-x-2 mx-1&quot;]/div[@class=&quot;w-20 sm:w-32&quot;]/button[@class=&quot;Button_root__0RbKd Button_primary__NGIIN Button_xl__w2v80&quot;]</value>
      <webElementGuid>d3796322-6953-4b3f-ae08-f51165ec3d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>4614a5ea-dedc-4813-abe1-0b4c223acfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div[2]/div/form/section/div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>7f6b1aeb-306e-4489-8d3f-0412153a402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>24692e8d-3048-44ef-bce9-f08133ef0cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>a3e0c3b9-d1a0-44c0-b3c8-198b7e7d8502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
