<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First NameLast NameTitleOrganizationCon_36d33f</name>
   <tag></tag>
   <elementGuidId>ca751136-6a2c-4b95-a292-7d9eaf8f15dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[5]/main/div[2]/div/form/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d6caa63-69ca-4aa1-8359-1064b4a1396d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col w-full sm:bg-secondary-accent space-y-8 sm:p-4 lg:p-[44px]</value>
      <webElementGuid>9caeff8a-0ed2-4eae-98b2-916f2aa3d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First NameLast NameTitleOrganizationContact No.EmailUser TypeSelect an option...defaultassistantadminflightaccommodationsside eventtransportationShow in App</value>
      <webElementGuid>00a4bbe0-b91e-4f36-95f5-9a2a8c88e8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/main[@class=&quot;flex&quot;]/div[@class=&quot;mt-s60 w-full duration-200 transition-all ml-auto content-width-minus-sidebar px-2 sm:px-8 pb-8&quot;]/div[1]/form[1]/div[@class=&quot;flex flex-col md:flex-row justify-between lg:w-[890px] space-y-10 md:space-y-0 md:space-x-4 text-white divide-y sm:divide-y-0 divide-[#4C4C4C]&quot;]/div[@class=&quot;flex flex-col w-full space-y-10 divide-y sm:divide-y-0 divide-[#4C4C4C] pt-10 sm:pt-0&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full sm:bg-secondary-accent space-y-8 sm:p-4 lg:p-[44px]&quot;]</value>
      <webElementGuid>a9377327-6848-49d9-a8d4-3f196cf67620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div[2]/div/form/div/div/div/div</value>
      <webElementGuid>f3e4c408-08f5-4483-94f9-11e97645dc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div</value>
      <webElementGuid>fc3567ef-b37b-43fc-8395-3a4d8e6495fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'First NameLast NameTitleOrganizationContact No.EmailUser TypeSelect an option...defaultassistantadminflightaccommodationsside eventtransportationShow in App' or . = 'First NameLast NameTitleOrganizationContact No.EmailUser TypeSelect an option...defaultassistantadminflightaccommodationsside eventtransportationShow in App')]</value>
      <webElementGuid>453404d6-14c4-42eb-bdb3-e78e15d9199e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
