<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_organization</name>
   <tag></tag>
   <elementGuidId>45ac2db7-3fde-425f-99e0-e8d4e2b36dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organization</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8c0fd37-057f-4310-9f0d-8e252b8cf36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>6aa2cb38-101e-4e23-bd33-0d3bf58ec376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>2c03111a-60a8-4736-ab09-1b7c9995b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>7e62a928-27a3-4264-93ca-0288ae09589d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex. NSC</value>
      <webElementGuid>7097ec8a-773c-4cd8-8861-7717cd3a9887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input_root__fi0ZK</value>
      <webElementGuid>1c468e85-d4f2-496e-bb7d-027ce122d968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization&quot;)</value>
      <webElementGuid>42cfbfe8-b444-43de-93dd-f2fd2d3565d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization']</value>
      <webElementGuid>575b4116-9be8-4b45-8c29-9bbb734590da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div[2]/div/form/div/div/div/div/div[4]/div[2]/input</value>
      <webElementGuid>baf0604b-570c-4a8d-a07f-b3e08b548da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>1703f2f9-8dc4-46c0-b6f7-6bb9fc176bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'organization' and @name = 'organization' and @placeholder = 'Ex. NSC']</value>
      <webElementGuid>e72f7775-85c9-48ed-96a8-628db716e929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
