<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_title</name>
   <tag></tag>
   <elementGuidId>892a39c7-8730-4cfa-a774-6217c076b542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>217dd78f-3aec-4bba-8765-ff38a7b4c316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a3675a55-3ae8-4148-ba0b-aab1ad7303ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>64fc830a-abbc-46e3-b173-7ebcf6086f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>481552a7-be9b-486c-b1fd-c7339c5ac9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex. Senator</value>
      <webElementGuid>3eb90cde-3224-441a-8381-a99ba27a9ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input_root__fi0ZK</value>
      <webElementGuid>4ab37740-0768-4711-85a4-6b9e5ede3e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title&quot;)</value>
      <webElementGuid>db2b4ac2-75d1-485c-9fc7-33d5f641d433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title']</value>
      <webElementGuid>d99ace6f-a1c7-4268-8133-59a13cd485a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div[2]/div/form/div/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>7df0b6fe-07bd-404a-9598-ec92a35ac6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>c6a14c38-4ade-4915-b114-24344f71a316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'title' and @name = 'title' and @placeholder = 'Ex. Senator']</value>
      <webElementGuid>5087f88c-0565-4b9e-ab49-3e537f728faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
