<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Input_root__fi0ZK</name>
   <tag></tag>
   <elementGuidId>cf68d4e4-5589-4354-97d5-fd13f9e154c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.items-center.space-x-s10 > div.flex.flex-col.w-full > div.relative.w-full > input.Input_root__fi0ZK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9418ab45-3d03-41d3-aaae-6e626019f33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4507201e-11ff-428e-ae2b-b9242fa8d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>dc57b868-1ef5-47cd-aae9-3ceef7a06ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>12246907-5dcf-4d88-a5c5-13f8e6b5ca75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input_root__fi0ZK</value>
      <webElementGuid>baeb047e-7c6e-416c-a8f2-4f1d5febd28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/main[@class=&quot;flex&quot;]/div[@class=&quot;mt-s60 w-full duration-200 transition-all ml-auto content-width-minus-sidebar px-2 sm:px-8 pb-8&quot;]/div[1]/form[1]/div[@class=&quot;flex flex-col md:flex-row justify-between lg:w-[890px] space-y-10 md:space-y-0 md:space-x-4 text-white divide-y sm:divide-y-0 divide-[#4C4C4C]&quot;]/div[@class=&quot;flex flex-col w-full space-y-10 divide-y sm:divide-y-0 divide-[#4C4C4C] pt-10 sm:pt-0&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full sm:bg-secondary-accent space-y-8 sm:p-4 lg:p-[44px]&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex items-center space-x-s10&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;Input_root__fi0ZK&quot;]</value>
      <webElementGuid>1fa72d24-ad69-4b28-8553-956cd5e714c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>a72d4f9b-9941-49e3-96bf-27f48e80c319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div[2]/div/form/div/div/div/div/div[5]/div[2]/div[2]/div/input</value>
      <webElementGuid>29039ae6-151c-4661-8c5f-93efacd213e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div/input</value>
      <webElementGuid>704c9042-afa0-4843-9efd-21bec4fc25d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Phone Number']</value>
      <webElementGuid>ff6a6dd4-2a8a-4d3d-a147-d4989b5baea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
