<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Attendees</name>
   <tag></tag>
   <elementGuidId>2c36217f-5ec0-467b-a8ad-558daaddcf83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[5]/main/div/aside/div/main/div[4]/div[2]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21abf13e-6e83-4264-8d0c-e950164d5d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_linkItem__9cKpC Button_root__0RbKd Button_ghost__tLrp+ Button_active__gXEPG SidebarMenuList_linkItem__n4oLf px-s10 py-s15</value>
      <webElementGuid>890c74de-cb41-45b5-8519-0522624da3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users</value>
      <webElementGuid>4017933f-98c0-44b6-9884-66ecf92e9fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendees</value>
      <webElementGuid>b22fdcd3-c6b8-48fb-a998-09777bc847de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/main[@class=&quot;flex&quot;]/div[@class=&quot;relative&quot;]/aside[@class=&quot;Sidebar_aside__UOHGl Sidebar_hideInMobile__NlErx&quot;]/div[@class=&quot;Sidebar_sidebarContainer__cv9HX sm:w-[230px]&quot;]/main[@class=&quot;pb-24 sm:pb-0&quot;]/div[@class=&quot;px-s15 relative flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full border-b border-secondary pt-s5 mb-s5 pb-s5&quot;]/div[@class=&quot;Collapsible_root__9wRN1 duration-500&quot;]/ul[1]/li[1]/a[@class=&quot;Button_linkItem__9cKpC Button_root__0RbKd Button_ghost__tLrp+ Button_active__gXEPG SidebarMenuList_linkItem__n4oLf px-s10 py-s15&quot;]</value>
      <webElementGuid>ab916cd9-f4a8-447c-b974-363f88aa1be7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div/aside/div/main/div[4]/div[2]/div/ul/li/a</value>
      <webElementGuid>90a30ff7-1334-4e58-8e82-e1cfc2ec25d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users')]</value>
      <webElementGuid>7fdae149-73ce-4c58-901d-dbe9764c3963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/ul/li/a</value>
      <webElementGuid>1e96be73-b4a4-4ff1-8407-ec2c444840cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users' and (text() = 'Attendees' or . = 'Attendees')]</value>
      <webElementGuid>0e9228d1-e469-451f-a74e-97cdcd0916d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
