<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Set Later Event 28-01-2024 162336</name>
   <tag></tag>
   <elementGuidId>b36ccfea-7322-402f-9465-de5c6dc9d046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td[@id='col-1']/div)[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bb10d8b4-033c-483b-bf26-eb0bf3f61a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Set Later Event: 28-01-2024 16:23:36</value>
      <webElementGuid>d92edb62-aa84-4f00-95db-6807bd9765ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/main[@class=&quot;flex&quot;]/div[@class=&quot;mt-s60 w-full duration-200 transition-all px-2 sm:px-8 pb-8&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;overflow-auto h-full w-full&quot;]/table[@class=&quot;min-w-full text-white text-center&quot;]/tbody[1]/tr[@class=&quot;h-[70px] border-b-2 border-primary-600 bg-primary-700&quot;]/td[@id=&quot;col-1&quot;]/div[1]</value>
      <webElementGuid>8a2798d4-cb3d-4b32-813e-f6d7e81e5f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='col-1']/div)[5]</value>
      <webElementGuid>c126e629-10f8-4d3e-8a3b-67faaf8cb434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div</value>
      <webElementGuid>67260942-7d39-490b-b077-c7daa67da3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Set Later Event: 28-01-2024 16:23:36' or . = 'Set Later Event: 28-01-2024 16:23:36')]</value>
      <webElementGuid>687def45-e70e-4a4c-80f9-541bfccdd342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
