<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Attendees</name>
   <tag></tag>
   <elementGuidId>08df5257-301c-4d97-8364-b3ee06d84c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[5]/main/div/aside/div/main/div[4]/div[2]/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7da73d3-3de8-4cec-8567-fced00406acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button_linkItem__9cKpC Button_root__0RbKd Button_ghost__tLrp+ SidebarMenuList_linkItem__n4oLf px-s10 py-s15</value>
      <webElementGuid>68a9e32d-1099-4ce7-99ac-3cb4df1ea5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users</value>
      <webElementGuid>0b5539f2-d068-4a3e-bbc3-a00336906e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendees</value>
      <webElementGuid>0daef226-4876-4ea1-b3db-50c81f1a09c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/main[@class=&quot;flex&quot;]/div[@class=&quot;relative&quot;]/aside[@class=&quot;Sidebar_aside__UOHGl Sidebar_hideInMobile__NlErx&quot;]/div[@class=&quot;Sidebar_sidebarContainer__cv9HX sm:w-[230px]&quot;]/main[@class=&quot;pb-24 sm:pb-0&quot;]/div[@class=&quot;px-s15 relative flex flex-col w-full&quot;]/div[@class=&quot;flex flex-col w-full border-b border-secondary pt-s5 mb-s5 pb-s5&quot;]/div[@class=&quot;Collapsible_root__9wRN1 duration-500&quot;]/ul[1]/li[1]/a[@class=&quot;Button_linkItem__9cKpC Button_root__0RbKd Button_ghost__tLrp+ SidebarMenuList_linkItem__n4oLf px-s10 py-s15&quot;]</value>
      <webElementGuid>d132f8c2-d9bd-4e85-bda4-953592ed4dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div/aside/div/main/div[4]/div[2]/div/ul/li/a</value>
      <webElementGuid>33202629-54fa-46af-a88a-9d61141abca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users')]</value>
      <webElementGuid>ac766584-100e-4cf7-bcc1-e424108ab7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/ul/li/a</value>
      <webElementGuid>b992fa05-a548-4566-bad8-ed217367112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/users' and (text() = 'Attendees' or . = 'Attendees')]</value>
      <webElementGuid>84cd0b0e-0749-4d3c-afb8-d01ccf69bbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
