<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an option.sss</name>
   <tag></tag>
   <elementGuidId>624f22b1-7b1c-4942-94a4-a99ac5ec6e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#entity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='entity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bfe7c9e6-dc65-4e3e-a978-e6611a72b69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input_root__fi0ZK Input_selectInput__aHlvF</value>
      <webElementGuid>9c98e720-1bcd-4708-8f18-d88514881f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>entity</value>
      <webElementGuid>9d89c645-61ff-40d3-8582-c3a7612784f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an option...sss</value>
      <webElementGuid>b73ad44d-5485-457f-bd56-d3818789bb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entity&quot;)</value>
      <webElementGuid>b5789545-ecf9-4ae5-8690-7288b23dfbe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='entity']</value>
      <webElementGuid>6a0c6702-c3c2-454e-ae96-c54518e91cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/main/div[2]/div/div[2]/div/div/div[2]/div/div[5]/div[2]/select</value>
      <webElementGuid>6460ec82-e15a-42cd-bd6b-11221d107e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>c000c38f-437a-4f6b-9fe7-deee6bda571f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'entity' and (text() = 'Select an option...sss' or . = 'Select an option...sss')]</value>
      <webElementGuid>4ba595ce-d274-4919-938a-81a3c195f6e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
